In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams
import csv
import requests
from bs4 import BeautifulSoup
import urllib2, urllib, json
import re
import datetime
import statsmodels.formula.api as smf # Regression library\n",
from datetime import datetime
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline

In [35]:
filename = '../Datasets/data/u.item.csv'
dfItem = pd.read_csv(filename, sep='\t', header=-1)
dfItem.head()

                                                   0
0  1|Toy Story (1995)|01-Jan-1995||http://us.imdb...
1  2|GoldenEye (1995)|01-Jan-1995||http://us.imdb...
2  3|Four Rooms (1995)|01-Jan-1995||http://us.imd...
3  4|Get Shorty (1995)|01-Jan-1995||http://us.imd...
4  5|Copycat (1995)|01-Jan-1995||http://us.imdb.c...

In [36]:
dfItem['movie id'] = map(lambda x: x.split('|')[0], dfItem[0])
dfItem['movie title'] = map(lambda x: x.split('|')[1], dfItem[0])
dfItem['video release date'] = map(lambda x: x.split('|')[2], dfItem[0])
dfItem['IMDB URL'] = map(lambda x: x.split('|')[4], dfItem[0])
dfItem['unknown'] = map(lambda x: x.split('|')[5], dfItem[0])
dfItem['Action'] = map(lambda x: x.split('|')[6], dfItem[0])
dfItem['Adventure'] = map(lambda x: x.split('|')[7], dfItem[0])
dfItem['Animation'] = map(lambda x: x.split('|')[8], dfItem[0])
dfItem['Children'] = map(lambda x: x.split('|')[9], dfItem[0])
dfItem['Comedy'] = map(lambda x: x.split('|')[10], dfItem[0])
dfItem['Crime'] = map(lambda x: x.split('|')[11], dfItem[0])
dfItem['Documentary'] = map(lambda x: x.split('|')[12], dfItem[0])
dfItem['Drama'] = map(lambda x: x.split('|')[13], dfItem[0])
dfItem['Fantasy'] = map(lambda x: x.split('|')[14], dfItem[0])
dfItem['Film-Noir'] = map(lambda x: x.split('|')[15], dfItem[0])
dfItem['Horror'] = map(lambda x: x.split('|')[16], dfItem[0])
dfItem['Musical'] = map(lambda x: x.split('|')[17], dfItem[0])
dfItem['Mystery'] = map(lambda x: x.split('|')[18], dfItem[0])
dfItem['Romance'] = map(lambda x: x.split('|')[19], dfItem[0])
dfItem['Sci-Fi'] = map(lambda x: x.split('|')[20], dfItem[0])
dfItem['Thriller'] = map(lambda x: x.split('|')[21], dfItem[0])
dfItem['War'] = map(lambda x: x.split('|')[22], dfItem[0])
dfItem['Western'] = map(lambda x: x.split('|')[23], dfItem[0])
del dfItem[0]

In [39]:
dfItem.to_csv("../Datasets/data/item.csv", index = False)
dfItem.head()

,movie id,movie title,video release date,IMDB URL,unknown,Action,Adventure,Animation,Children,Comedy,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0